GET ME
amangalick/ucce pull request #2
Opened 2024-02-23 03:16 UTC by meaganvu

2024-02-23 03:19 UTC, walkerselby requested changes
For the future, you don't need to include the .DS_Store. You can also add that to your .gitignore

2024-02-23 19:13 UTC, amangalick approved these changes

2024-02-23 19:15 UTC, amangalick approved these changes

2024-03-08 02:23 UTC, amangalick approved these changes

2024-03-08 02:42 UTC, merged